[tool.ruff.lint]
select = ["ALL"] # Enable all linters.
ignore = [
    # S603 and S602 overlap where one or the other is always true. S603 is disabled
    # because S602 is more secure than S603.
    "S603",

    # This rule makes it impossible to access URLs that are dynamically created.
    "S310",

    # Docstrings should exist when they are useful, requiring them just leads to bad
    # docstrings.
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    #
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101"] # Asserts should be allowed in tests.
